version: '3'

services:
  backend:
    build: .
    restart: no
    environment:
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DIALECT: ${DB_DIALECT}
      PASSWORD_HASH_SALT: ${PASSWORD_HASH_SALT}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_FULL_NAME: ${ADMIN_FULL_NAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_HOST: db
    ports:
      - "8080:8080"
  db:
    image: mysql:latest
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./.ignoreme/db_data:/var/lib/mysql
